In [ ]:
import tensorflow as tf

# Create tensor

with tf.compat.v1.Session() as sec:
    hello = tf.strings.join(["Hello, World"])

# Launch session

sess = tf.compat.v1.Session()

print(sess.run(hello))


In [ ]:

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

# Create tensor

hello = tf.strings.join(["Hello, World"])

# Launch session

sess = tf.compat.v1.Session()

print(sess.run(hello))


In [ ]:
a = tf.constant(2.0)
b = tf.constant(2.0)
c = a * b
sess = tf.compat.v1.Session()
print(sess.run(c))

In [ ]:
import numpy as np
a = tf.placeholder(np.float32)
b = tf.placeholder(np.float32)
c= a+b
sess = tf.Session()

#initialize all variables

sess.run(tf.initialize_all_variables())
feed_dict = {a:2, b:3}
#now run the sum operation
ppx = sess.run([c], feed_dict)

#print the result
print(ppx)



In [19]:
import numpy as np
import tensorflow as tf
@tf.function
def sum_even(items):
    s = 0
    for c in items:
        if tf.equal(c % 2, 0):
            s += c
    return s
sum_even(tf.constant([10, 12, 15, 20])).numpy()




42

In [54]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
x=tf.constant(22) #= tf.constant(int(input("enter number :")))
y =tf.constant(2)#= tf.constant(int(input("enter number :")))
z =tf.constant(23)
# z =tf.constant(int(input("1*2/3+4-")) )
# def f1(): return tf.constant(17)

# r = tf.case([(tf.equal(z,1), f1)],default=f3, exclusive=True)

def f1(): return tf.sum(x,y)
def f2(): return tf
def f3(): return tf.constant(-1)
r = tf.case([(tf.less(x, y), f1), (tf.greater(x, z), f2)],
         default=f3, exclusive=True)
print(r)

Tensor("case_14/cond/Merge:0", shape=(), dtype=int32)


In [89]:
import tensorflow.compat.v1 as tf
#x= tf.constant(int(input("enter number :")))
#y= tf.constant(int(input("enter number :")))
x=tf.constant(22)
y=tf.constant(22)

def f1(): return tf.multiply(x,y)
def f2(): return tf.add(x,y)
def f3(): return tf.subtract(x,y)

ip=int(input(" 1 \t * \n 2 \t + \n 3 \t -\n"))-1
branch_index=tf.constant(ip)
# print(branch_index)

switch = tf.switch_case(branch_index, branch_fns={0: f1, 1: f2}, default=f3)
sess = tf.Session()
res=sess.run(switch)
print("\n result=",res)

 1 	 * 
 2 	 + 
 3 	 -
1

 result= 484


In [90]:
import tensorflow as tf

t1 = tf.constant([1, 2, 3])
t2 = tf.constant([[1.1, 2.2, 3.3], [4, 5, 6]])
t3 = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
t4 = tf.constant(["India", "Australia"])
t5 = tf.constant([15.5, 20.5, 35.5, 40.1, 80.5])

sess = tf.compat.v1.Session()
 
print(t1)
print(t2)
 
print("\n########################\n")
print(t3)
print(sess.run(t3))
print("\n########################\n")
 
print(t4)
 
print("\n########################\n")
print(t5)
print(sess.run(t5))
print("\n########################\n")


Tensor("Const_167:0", shape=(3,), dtype=int32)
Tensor("Const_168:0", shape=(2, 3), dtype=float32)

########################

Tensor("Const_169:0", shape=(3, 3), dtype=int32)
[[1 2 3]
 [4 5 6]
 [7 8 9]]

########################

Tensor("Const_170:0", shape=(2,), dtype=string)

########################

Tensor("Const_171:0", shape=(5,), dtype=float32)
[15.5 20.5 35.5 40.1 80.5]

########################



In [92]:
# TensorFlow program to create tensor using zeros function.
 
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
 
import tensorflow as tf
zero_tensor = tf.zeros([3])
zero_tensor_int = tf.zeros([3], tf.int32, 'ZeroTensor')
zero_tensor_4x_4x_4x = tf.zeros([4, 4, 4], tf.int8, '4X-ZeroTensor')
 
print(zero_tensor)
print(zero_tensor_int)
print(zero_tensor_4x_4x_4x)
 
sess = tf.compat.v1.Session()
print(sess.run(zero_tensor_4x_4x_4x))

Tensor("zeros_1:0", shape=(3,), dtype=float32)
Tensor("ZeroTensor_1:0", shape=(3,), dtype=int32)
Tensor("4X-ZeroTensor_1:0", shape=(4, 4, 4), dtype=int8)
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [93]:
##
# TensorFlow program to create tensor using fill function.
 
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
 
import tensorflow as tf
fill_tensor = tf.fill([3], 10)
fill_tensor_2x_2x = tf.fill([2, 2], 15, '2x-Fill-Tensor')
fill_tensor_string = tf.fill([2, 2], "Japan", 'String-Fill-Tensor')
fill_tensor_4x_4x_4x = tf.fill([4, 4, 4], 10.15, '4X-Fill-Tensor')
sess = tf.compat.v1.Session()
 
print(fill_tensor)
print(sess.run(fill_tensor))
print("\n########################\n")
 
print(fill_tensor_2x_2x)
print(sess.run(fill_tensor_2x_2x))
print("\n########################\n")
 
print(fill_tensor_string)
print(sess.run(fill_tensor_string))
print("\n########################\n")
 
print(fill_tensor_4x_4x_4x)
print(sess.run(fill_tensor_4x_4x_4x))
print("\n########################\n")



Tensor("Fill:0", shape=(3,), dtype=int32)
[10 10 10]

########################

Tensor("2x-Fill-Tensor:0", shape=(2, 2), dtype=int32)
[[15 15]
 [15 15]]

########################

Tensor("String-Fill-Tensor:0", shape=(2, 2), dtype=string)
[[b'Japan' b'Japan']
 [b'Japan' b'Japan']]

########################

Tensor("4X-Fill-Tensor:0", shape=(4, 4, 4), dtype=float32)
[[[10.15 10.15 10.15 10.15]
  [10.15 10.15 10.15 10.15]
  [10.15 10.15 10.15 10.15]
  [10.15 10.15 10.15 10.15]]

 [[10.15 10.15 10.15 10.15]
  [10.15 10.15 10.15 10.15]
  [10.15 10.15 10.15 10.15]
  [10.15 10.15 10.15 10.15]]

 [[10.15 10.15 10.15 10.15]
  [10.15 10.15 10.15 10.15]
  [10.15 10.15 10.15 10.15]
  [10.15 10.15 10.15 10.15]]

 [[10.15 10.15 10.15 10.15]
  [10.15 10.15 10.15 10.15]
  [10.15 10.15 10.15 10.15]
  [10.15 10.15 10.15 10.15]]]

########################



In [94]:

import tensorflow as tf
linspace_tensor = tf.linspace(5.0, 10.0, 5, "Linspace-Tensor")
linspace_tensor_dec = tf.linspace(100.0, 20.0, 20, "Linspace-Tensor-Down")
sess = tf.compat.v1.Session()
 
print(linspace_tensor)
print(sess.run(linspace_tensor))
print("\n########################\n")
 
print(linspace_tensor_dec)
print(sess.run(linspace_tensor_dec))


Tensor("Linspace-Tensor/Slice:0", shape=(5,), dtype=float32)
[ 5.    6.25  7.5   8.75 10.  ]

########################

Tensor("Linspace-Tensor-Down/Slice:0", shape=(20,), dtype=float32)
[100.        95.789474  91.57895   87.36842   83.1579    78.94737
  74.73684   70.52631   66.31579   62.105263  57.894737  53.684208
  49.473682  45.263157  41.052628  36.842102  32.631577  28.421051
  24.210526  20.      ]


In [95]:
import tensorflow as tf
range_tensor = tf.range(20.0, 100.0, delta=15.5)
range_tensor_delta = tf.range(100.0, delta=15.5, name="Range-Tensor")
sess = tf.compat.v1.Session()
 
print(range_tensor)
print(sess.run(range_tensor))
print("\n########################\n")
 
print(range_tensor_delta)
print(sess.run(range_tensor_delta))
print("\n########################\n")


Tensor("range:0", shape=(6,), dtype=float32)
[20.  35.5 51.  66.5 82.  97.5]

########################

Tensor("Range-Tensor:0", shape=(7,), dtype=float32)
[ 0.  15.5 31.  46.5 62.  77.5 93. ]

########################



In [96]:
import tensorflow as tf
random_normal_tensor = tf.random.normal([10], mean=1.0, stddev=2.0,
                                        dtype=tf.float64, name="RNT")
 
random_uniform_tensor = tf.random.uniform([10], minval=0.0, maxval=5.0,
                                          dtype=tf.float64, name="RUT")
sess = tf.compat.v1.Session()
print("\n--------------------------     RANDOM NORMAL   ------------------\n")
print(random_normal_tensor)
print(sess.run(random_normal_tensor))
print("\n-----------------------------------------------------------------\n")
 
print("\n--------------------------     RANDOM UNIFROM  ------------------\n")
print(random_uniform_tensor)
print(sess.run(random_uniform_tensor))
print("---------------------------------------------------------------------")




--------------------------     RANDOM NORMAL   ------------------

Tensor("RNT:0", shape=(10,), dtype=float64)
[-0.34064193  4.30710676  3.59750487 -1.41286625  2.14947099  1.67891937
  1.67808956  0.99808282 -0.68974314  1.71557364]

-----------------------------------------------------------------


--------------------------     RANDOM UNIFROM  ------------------

Tensor("RUT:0", shape=(10,), dtype=float64)
[0.99500728 2.40773057 0.0444392  4.81911375 0.26385767 2.03512842
 4.11517952 4.81721658 0.10539152 0.64811462]
---------------------------------------------------------------------
