In [19]:
import numpy as np
import tensorflow as tf
@tf.function
def sum_even(items):
    s = 0
    for c in items:
        if tf.equal(c % 2, 0):
            s += c
    return s
sum_even(tf.constant([10, 12, 15, 20])).numpy()




42

In [54]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
x=tf.constant(22) #= tf.constant(int(input("enter number :")))
y =tf.constant(2)#= tf.constant(int(input("enter number :")))
z =tf.constant(23)
# z =tf.constant(int(input("1*2/3+4-")) )
# def f1(): return tf.constant(17)

# r = tf.case([(tf.equal(z,1), f1)],default=f3, exclusive=True)

def f1(): return tf.sum(x,y)
def f2(): return tf
def f3(): return tf.constant(-1)
r = tf.case([(tf.less(x, y), f1), (tf.greater(x, z), f2)],
         default=f3, exclusive=True)
print(r)

Tensor("case_14/cond/Merge:0", shape=(), dtype=int32)


In [89]:
import tensorflow.compat.v1 as tf
#x= tf.constant(int(input("enter number :")))
#y= tf.constant(int(input("enter number :")))
x=tf.constant(22)
y=tf.constant(22)

def f1(): return tf.multiply(x,y)
def f2(): return tf.add(x,y)
def f3(): return tf.subtract(x,y)

ip=int(input(" 1 \t * \n 2 \t + \n 3 \t -\n"))-1
branch_index=tf.constant(ip)
# print(branch_index)

switch = tf.switch_case(branch_index, branch_fns={0: f1, 1: f2}, default=f3)
sess = tf.Session()
res=sess.run(switch)
print("\n result=",res)

 1 	 * 
 2 	 + 
 3 	 -
1

 result= 484


In [90]:
import tensorflow as tf

t1 = tf.constant([1, 2, 3])
t2 = tf.constant([[1.1, 2.2, 3.3], [4, 5, 6]])
t3 = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
t4 = tf.constant(["India", "Australia"])
t5 = tf.constant([15.5, 20.5, 35.5, 40.1, 80.5])

sess = tf.compat.v1.Session()
 
print(t1)
print(t2)
 
print("\n########################\n")
print(t3)
print(sess.run(t3))
print("\n########################\n")
 
print(t4)
 
print("\n########################\n")
print(t5)
print(sess.run(t5))
print("\n########################\n")


Tensor("Const_167:0", shape=(3,), dtype=int32)
Tensor("Const_168:0", shape=(2, 3), dtype=float32)

########################

Tensor("Const_169:0", shape=(3, 3), dtype=int32)
[[1 2 3]
 [4 5 6]
 [7 8 9]]

########################

Tensor("Const_170:0", shape=(2,), dtype=string)

########################

Tensor("Const_171:0", shape=(5,), dtype=float32)
[15.5 20.5 35.5 40.1 80.5]

########################



In [92]:
# TensorFlow program to create tensor using zeros function.
 
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
 
import tensorflow as tf
zero_tensor = tf.zeros([3])
zero_tensor_int = tf.zeros([3], tf.int32, 'ZeroTensor')
zero_tensor_4x_4x_4x = tf.zeros([4, 4, 4], tf.int8, '4X-ZeroTensor')
 
print(zero_tensor)
print(zero_tensor_int)
print(zero_tensor_4x_4x_4x)
 
sess = tf.compat.v1.Session()
print(sess.run(zero_tensor_4x_4x_4x))

Tensor("zeros_1:0", shape=(3,), dtype=float32)
Tensor("ZeroTensor_1:0", shape=(3,), dtype=int32)
Tensor("4X-ZeroTensor_1:0", shape=(4, 4, 4), dtype=int8)
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
